### ISSUE TITLE
Run time error when loading rule sets

### ISSUE THREAD

**Issue by marcus67** [marcus67/rechtschreibung#20]
Traceback (most recent call last):
  File "/var/mobile/Containers/Bundle/Application/4691DC68-0706-4F8A-9781-FE09D95BCE2F/Pythonista.app/Frameworks/PythonistaKit.framework/pylib/site-packages/ui.py", line 126, in tableview_did_select
    self.action(self)
  File "/private/var/mobile/Containers/Shared/AppGroup/840290D8-E955-40F9-92F1-35978306EC02/Documents/rechtschreibung/mode_selector.py", line 105, in handle_action
    if self.parent_view:
AttributeError: 'SpellingModeSelector' object has no attribute 'parent_view'

**Comment by marcus67** [comment]
close issue in previous commit
